# AUTOGENERATED! DO NOT EDIT! File to edit: ../../app.ipynb.

# %% auto 0
__all__ = ['temp', 'learn', 'categories', 'image', 'label', 'examples', 'intf', 'is_cat', 'classify_image']

# %% ../../app.ipynb 1
from fastai.vision.all import *
import gradio as gr

def is_cat(x):
    return x[0].isupper()

# %% ../../app.ipynb 11
import pathlib

# model_path = str(pathlib.Path('model.pkl').absolute())

if os.name == 'posix':
    model_path = str(pathlib.PosixPath('model.pkl').absolute())  # Unix-like systems
else:
    # model_path = str(pathlib.WindowsPath('model.pkl').absolute())  # Windows systems
    temp = pathlib.PosixPath
    pathlib.PosixPath = pathlib.WindowsPath
    model_path = 'model.pkl'

learn = load_learner(model_path)

# %% ../../app.ipynb 13
categories = ('Dog', 'Cat')

def classify_image(img):
    pred, idx, probs = learn.predict(img)
    return dict(zip(categories, map(float, probs)))

# %% ../../app.ipynb 16
# Create an image input component without specifying the shape
image = gr.Image()
label = gr.Label()
examples = ['dog.jpg', 'cat.jpg']

intf = gr.Interface(fn=classify_image, inputs=image, outputs=label, examples=examples)
intf.launch(inline=False)
